pub struct CardInfo {
    name: String,
    attribute: String,
    types: String,
    level: String,
    attack: i32,
    defense: i32,
    cardNum: String,
    passcode: String,
    effectTypes: String,
    materials: String,
    fusionMaterials: String,
    rank: String,
    ritualSpell: String,
    pendulumScale: String,
    typeSpellTrap: String,
    property: String,
    summonedBy: String,
    limitText: String,
    synchroMaterial: String,
    ritualMonster: String,
    //
    ruling: String,
    tips: String,
    trivia: String,
    lore: String,
    ocgStatus: String,
    tcgAdvStatus: String,
    tcgTrnStatus: String
}
